import { NavDropdownItem } from '../../types';

export const navLinks: NavDropdownItem[] = [
  {
    section: 'new arrivals',
    men: ['Adidas', 'Nike', 'Air Jordan'],
    women: ['Adidas', 'Nike', 'Air Jordan'],
    kid: ['Adidas', 'Nike', 'Air Jordan'],
  },
  {
    section: 'most wanted',
    men: ['Adidas', 'Nike', 'Air Jordan', 'Supreme', 'Yeezy'],
    women: ['Adidas', 'Nike', 'Air Jordan', 'Puma', 'Supreme', 'Yeezy'],
    kid: ['Adidas', 'Nike', 'Air Jordan'],
  },
  {
    section: 'shoes',
    men: [
      'Adidas',
      'Nike',
      'Air Jordan',
      'Converse',
      'Vans',
      'New Balance',
      'Reebok',
    ],
    women: [
      'Adidas',
      'Nike',
      'Air Jordan',
      'Converse',
      'New Balance',
      'Timberland',
      'Native',
      'Vans',
      'Asics',
    ],
    kid: ['Adidas', 'Nike', 'Air Jordan', 'Converse', 'Vans'],
  },
  {
    section: 'apparel',
    men: ['Adidas', 'Nike', 'Air Jordan'],
    women: ['Adidas', 'Nike', 'Air Jordan'],
    kid: ['Adidas', 'Nike', 'Air Jordan'],
  },
  {
    section: 'gear',
    men: ['Diadora', 'Native', 'Adidas', 'Nike'],
    women: ['Adidas', 'Nike', 'Air Jordan'],
    kid: ['Adidas', 'Nike', 'Air Jordan'],
  },
  {
    section: 'sale',
    men: ['Adidas', 'Nike', 'Air Jordan', 'Asics'],
    women: [
      'Adidas',
      'Nike',
      'Air Jordan',
      'New Balance',
      'Timberland',
      'Native',
      'Vans',
      'Asics',
    ],
    kid: [
      'Adidas',
      'Nike',
      'Air Jordan',
      'Timberland',
      'Native',
      'Vans',
      'Asics',
    ],
  },
];
